[package]
name = "ipa-translate"
description = "A crate for translating ASCII text to IPA"
version = "0.1.1"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tirimid/ipa-translate"

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.0"
